services:
  passwordnow:
    container_name: "PasswordNow"
    image: passwordnow
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:8080"
      - "8001:8081"